# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
container: 'rust:latest'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    export PATH=$PATH:$HOME/.cargo/bin
    rustup toolchain install stable
    rustup default stable
    rustup component add clippy
    rustup component add rustfmt
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"

- script: cargo build --all
  displayName: Cargo build

- script: cargo test --all
  displayName: Cargo test
