name: Rust Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.20
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379:2379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build
        run: cargo build

      - name: Run tests
        env:
          ETCD_ENDPOINTS: "http://localhost:2379"
        run: cargo test --test test_kv

  test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.20
        env:
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 2379:2379
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run tests
        env:
          ETCD_ENDPOINTS: "http://localhost:2379"
        run: cargo test --test test_kv

      - name: Enable etcd authentication and create user
        run: |
          docker exec "${{ job.services.etcd.id }}" etcdctl user add root:123456
          docker exec "${{ job.services.etcd.id }}" etcdctl user grant-role root root
          docker exec "${{ job.services.etcd.id }}" etcdctl auth enable

      - name: Run tests with authentication
        env:
          ETCD_ENDPOINTS: "http://localhost:2379"
        run: cargo test --test test_authenticated
